### ISSUE TITLE
Task Scheduling

### ISSUE THREAD

**Issue by ocarlosapenas** [ocarlosapenas/code-studies-laravel#102]
Task Scheduling #40

- [ ] Scheduling Artisan Commands #40
- [ ] Scheduling Queue Jobs #40
- [ ] Scheduling Shell Commands #40
- [ ] Time Zones #40
- [ ] Preventing Task Overlaps #40
- [ ] Maintenance Mode #40
