### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ocarlosapenas** [ocarlosapenas/code-studies-laravel#103]
- [ ] Creating / Running Tests #59
- [ ] HTTP Tests #60 
- [ ] Session / Authentication #60 
- [ ] Testing File Uploads #60 
- [ ] Available Assertions #60
- [ ] Browser Tests / Dusk #62 
- [ ] Data Factories #63 
- [ ] Fakes / Mocking #64
