### ISSUE TITLE
Queues

### ISSUE THREAD

**Issue by ocarlosapenas** [ocarlosapenas/code-studies-laravel#98]
Queues #38

- [ ] Drivers / Configurations #38
- [ ] Creating / Dispatching Jobs #38
- [ ] Running Queue Workers #38
- [ ] Supervisor #38
- [ ] Handling Failed Jobs #38
